### PR TITLE
Migrate to Tycho 3.0.1

### PR DESCRIPTION
**Pull request by fbricon**
Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by fbricon** [comment]
https://github.com/jbosstools/m2e-wro4j/actions/runs/3882720524/jobs/6623197201

```
Error:  Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository (default-assemble-repository) on project org.jboss.tools.m2e.wro4j.site: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository failed: An API incompatibility was encountered while executing org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository: java.lang.NoSuchMethodError: 'void org.eclipse.equinox.internal.p2.repository.helpers.ChecksumProducer.<init>(java.lang.String, java.lang.String, java.lang.String)'
```

Build works locally. @mickaelistria does it ring any bell?

**Comment by mickaelistria** [comment]
Is it possible for you to try clearing the remote .m2 repo or other caches, if any exists?

**Comment by fbricon** [comment]
Same error after [cleaning the Maven cache](https://github.com/jbosstools/m2e-wro4j/actions/runs/3882720524/jobs/6625481891#step:4:14)

Tested on my Linux box, same JDK, no problem

**Comment by fbricon** [comment]
I could reproduce locally on my Linux box by cleaning my local .m2 repo

**Comment by fbricon** [comment]
Found https://github.com/eclipse-tycho/tycho/issues/1814. Switching to tycho 3.0.1 fixed it.

**Pull request merged**
